services:
  frontend:
    build:
      context: ./web
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - internal
    volumes:
      - shared-data:/app/src/data
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend/data:/app/data
      - shared-data:/app/data/web
    networks:
      - internal
    ports:
      - "8000:8000"

volumes:
  shared-data:

networks:
  internal:
    driver: bridge
